name: Build & test with Gradle

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 

    - name: 'Set up JDK'
      uses: 'actions/setup-java@v4'
      with:
        java-version: '20'
        distribution: 'zulu'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Run build
      run: ./gradlew build

    - name: Run tests
      run: ./gradlew test
